[phases.setup]
nixPkgs = ["bun", "nodejs"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build --filter=deployment-service"]

[start]
cmd = "cd apps/deployment-service && node dist/index.js"
