providers = ["node"]

[phases.setup]
nixPkgs = ["bun", "nodejs"]

[phases.install]
cmds = ["bun install"]

[build]
cmd = "bun run build:railway"

[phases.start]
cmd = "cd apps/deployment-service && bun dist/index.js"
