[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "erc721a/=lib/ERC721A/"
]

# Habilitar IR y optimizer para resolver stack overflow
viaIR = true
optimizer = true
optimizer_runs = 200

# Excluir contratos experimentales que tienen errores conocidos
skip = [
    'contracts/experimental/*'
]
